#############################################################################
# Makefile for building: puzzle_shuzhou
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Apr 14 20:34:08 2013
# Project:  puzzle_shuzhou.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile puzzle_shuzhou.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = board.cpp \
		graphicswindow.cpp \
		guitile.cpp \
		hlayout.cpp \
		intoolbar.cpp \
		main_window.cpp \
		mylayout.cpp \
		pmminlist.cpp \
		puzzle_heur.cpp \
		puzzle_move.cpp \
		puzzle_solver.cpp \
		qtpuzzle.cpp moc_guitile.cpp \
		moc_hlayout.cpp \
		moc_intoolbar.cpp \
		moc_main_window.cpp \
		moc_mylayout.cpp
OBJECTS       = board.o \
		graphicswindow.o \
		guitile.o \
		hlayout.o \
		intoolbar.o \
		main_window.o \
		mylayout.o \
		pmminlist.o \
		puzzle_heur.o \
		puzzle_move.o \
		puzzle_solver.o \
		qtpuzzle.o \
		moc_guitile.o \
		moc_hlayout.o \
		moc_intoolbar.o \
		moc_main_window.o \
		moc_mylayout.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		puzzle_shuzhou.pro
QMAKE_TARGET  = puzzle_shuzhou
DESTDIR       = 
TARGET        = puzzle_shuzhou

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: puzzle_shuzhou.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile puzzle_shuzhou.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile puzzle_shuzhou.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/puzzle_shuzhou1.0.0 || $(MKDIR) .tmp/puzzle_shuzhou1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/puzzle_shuzhou1.0.0/ && $(COPY_FILE) --parents board.h graphicswindow.h guitile.h hlayout.h intoolbar.h main_window.h mylayout.h mylist.h pmminlist.h puzzle_heur.h puzzle_move.h puzzle_solver.h .tmp/puzzle_shuzhou1.0.0/ && $(COPY_FILE) --parents board.cpp graphicswindow.cpp guitile.cpp hlayout.cpp intoolbar.cpp main_window.cpp mylayout.cpp pmminlist.cpp puzzle_heur.cpp puzzle_move.cpp puzzle_solver.cpp qtpuzzle.cpp .tmp/puzzle_shuzhou1.0.0/ && (cd `dirname .tmp/puzzle_shuzhou1.0.0` && $(TAR) puzzle_shuzhou1.0.0.tar puzzle_shuzhou1.0.0 && $(COMPRESS) puzzle_shuzhou1.0.0.tar) && $(MOVE) `dirname .tmp/puzzle_shuzhou1.0.0`/puzzle_shuzhou1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/puzzle_shuzhou1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_guitile.cpp moc_hlayout.cpp moc_intoolbar.cpp moc_main_window.cpp moc_mylayout.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_guitile.cpp moc_hlayout.cpp moc_intoolbar.cpp moc_main_window.cpp moc_mylayout.cpp
moc_guitile.cpp: guitile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) guitile.h -o moc_guitile.cpp

moc_hlayout.cpp: hlayout.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) hlayout.h -o moc_hlayout.cpp

moc_intoolbar.cpp: main_window.h \
		graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h \
		mylayout.h \
		hlayout.h \
		intoolbar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) intoolbar.h -o moc_intoolbar.cpp

moc_main_window.cpp: graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h \
		mylayout.h \
		hlayout.h \
		main_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) main_window.h -o moc_main_window.cpp

moc_mylayout.cpp: graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h \
		mylayout.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mylayout.h -o moc_mylayout.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

board.o: board.cpp board.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o board.o board.cpp

graphicswindow.o: graphicswindow.cpp graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicswindow.o graphicswindow.cpp

guitile.o: guitile.cpp guitile.h \
		graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o guitile.o guitile.cpp

hlayout.o: hlayout.cpp hlayout.h \
		main_window.h \
		graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h \
		mylayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hlayout.o hlayout.cpp

intoolbar.o: intoolbar.cpp intoolbar.h \
		main_window.h \
		graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h \
		mylayout.h \
		hlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intoolbar.o intoolbar.cpp

main_window.o: main_window.cpp main_window.h \
		graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h \
		mylayout.h \
		hlayout.h \
		intoolbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_window.o main_window.cpp

mylayout.o: mylayout.cpp mylayout.h \
		graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mylayout.o mylayout.cpp

pmminlist.o: pmminlist.cpp puzzle_move.h \
		board.h \
		puzzle_heur.h \
		pmminlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pmminlist.o pmminlist.cpp

puzzle_heur.o: puzzle_heur.cpp puzzle_heur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o puzzle_heur.o puzzle_heur.cpp

puzzle_move.o: puzzle_move.cpp puzzle_move.h \
		board.h \
		puzzle_heur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o puzzle_move.o puzzle_move.cpp

puzzle_solver.o: puzzle_solver.cpp puzzle_solver.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		mylist.h \
		pmminlist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o puzzle_solver.o puzzle_solver.cpp

qtpuzzle.o: qtpuzzle.cpp main_window.h \
		graphicswindow.h \
		board.h \
		puzzle_move.h \
		puzzle_heur.h \
		puzzle_solver.h \
		mylist.h \
		pmminlist.h \
		guitile.h \
		mylayout.h \
		hlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtpuzzle.o qtpuzzle.cpp

moc_guitile.o: moc_guitile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_guitile.o moc_guitile.cpp

moc_hlayout.o: moc_hlayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hlayout.o moc_hlayout.cpp

moc_intoolbar.o: moc_intoolbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_intoolbar.o moc_intoolbar.cpp

moc_main_window.o: moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_window.o moc_main_window.cpp

moc_mylayout.o: moc_mylayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mylayout.o moc_mylayout.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

